import type { Effect, Killer, KillerAction } from '../../types';

const base = 'assets/killers/dr-fright';
const ka = (target: KillerAction['target'], moves: number, attacks: number): Effect => ({
  kind: 'killerAction',
  action: { target, moves, attacks },
});
const custom = (id: string): Effect => ({ kind: 'custom', id });
const terror = (amount: number): Effect => ({ kind: 'terror', amount });
const row = (attack: number, move: number, effects: Effect[] = [], revealDarkPower = false) => ({
  attack,
  move,
  effects,
  ...(revealDarkPower ? { revealDarkPower } : {}),
});

/**
 * Dr. Fright (el Doctor de los Sueños): solo puede dañarte (y tú a él) cuando estás Dormida en la Sala de Calderas.
 * Despierta se le puede esquivar, pero la Sala de Calderas siempre acaba reclamándote.
 */
export const DR_FRIGHT: Killer = {
  id: 'dr-fright',
  name: 'Dr. Fright',
  film: 'maple',
  icon: 'pitchfork',
  board: `${base}/board.webp`,
  cover: `${base}/cover.webp`,
  token: `${base}/token.webp`,
  select: `${base}/select.webp`,
  startTerror: 4,
  health: 9,
  // Medidor de Sed de Sangre, de abajo a arriba (leído del tablero).
  bloodlust: [
    row(1, 1),
    row(1, 1, [terror(1)]),
    row(1, 2),
    row(2, 2, [terror(1)]),
    row(2, 2, [], true),
    row(2, 2),
    row(3, 2, [terror(1)]),
    row(3, 3),
    row(3, 3, [terror(2)]),
    row(4, 4),
  ],
  // "Si estás Dormida reinicia el mazo de Sala de Calderas. De lo contrario: te quedas Dormida."
  bloodlustMaxEffect: [custom('df-bloodlust-max')],
  bloodlustMaxText: 'si estás Dormida se reinicia el mazo de la Sala de Calderas; si no, te quedas Dormida',
  // Reverso del Gran Final: el más cercano ▶ atacar.
  initialAction: [ka('nearest', 0, 1)],
  finaleBack: `${base}/finale/back.webp`,
  darkPowerBack: `${base}/dark-power/back.webp`,
  finales: [
    {
      id: 'deben-morir-todos',
      name: 'Deben morir todos',
      image: `${base}/finale/deben-morir-todos.webp`,
      finalAction: [custom('df-kill-two')],
      text: 'Al revelarse, el Dr. Fright sale del tablero y se pone en esta carta. El resto de la partida puede ser atacado desde cualquier espacio si estás Dormida. Cada fase del Asesino: mata a 2 Víctimas automáticamente (tú eliges cuáles); si no hay ninguna, pierdes 4 Vidas.',
      custom: 'finale-ml-everyone-dies',
    },
    {
      id: 'afronta-tu-miedo',
      name: 'Afronta tu miedo',
      image: `${base}/finale/afronta-tu-miedo.webp`,
      finalAction: [ka('nearest', 1, 1)],
      text: 'Si estás Despierta cuando se revela, caes Dormida. Mientras esta carta esté en juego, estás Dormida hasta el fin del juego; la Sala de Calderas se reinicia inmediatamente al salir.',
      custom: 'finale-ml-fear',
    },
    {
      id: 'hora-de-morir',
      name: 'Hora de morir',
      image: `${base}/finale/hora-de-morir.webp`,
      finalAction: [ka('finalGirl', 1, 2)],
      text: 'Si estás Despierta en el Mantenimiento, pierdes 2 Vidas y caes Dormida.',
      custom: 'finale-ml-time',
    },
  ],
  darkPowers: [
    {
      id: 'asalto-del-tridente',
      name: 'Asalto del tridente',
      image: `${base}/dark-power/asalto-del-tridente.webp`,
      text: 'Cada vez que el Dr. Fright te cause daño, +1 Terror.',
      custom: 'dp-ml-trident',
    },
    {
      id: 'nunca-realmente-muerto',
      name: 'Nunca realmente muerto',
      image: `${base}/dark-power/nunca-realmente-muerto.webp`,
      text: 'Cuando se revela, devuelve a la reserva la ficha negra de Vida Final del Dr. Fright y sustitúyela por una blanca. Si pierde su última Vida, revela 3 fichas negras de Vida Final de la reserva y restaura su Vida con ellas.',
      custom: 'dp-ml-never-dead',
    },
    {
      id: 'frightsadilla-inevitable',
      name: 'La Frightsadilla es inevitable',
      image: `${base}/dark-power/frightsadilla-inevitable.webp`,
      text: 'El Dr. Fright te puede atacar aunque estés Despierta.',
      custom: 'dp-ml-frightsadilla',
    },
    {
      id: 'factor-sorpresa',
      name: 'Factor sorpresa',
      image: `${base}/dark-power/factor-sorpresa.webp`,
      text: 'Poder Oscuro Épico. Si una Víctima entra en pánico, en su lugar es asesinada (máximo 3 por turno).',
      epic: true,
      custom: 'dp-ml-surprise',
    },
  ],
  horror: [
    {
      id: 'acuchillala',
      name: 'Acuchíllala',
      copies: 1,
      image: `${base}/horror/acuchillala.webp`,
      text: 'El más cercano ▶ atacar. Después: el más cercano ▶ mover ▶ atacar. Todas las Víctimas que no estén en una Casa entran en pánico.',
      effects: [ka('nearest', 0, 1), ka('nearest', 1, 1), custom('df-panic-outside')],
    },
    {
      id: 'no-puedes-estar-aqui',
      name: '«No puedes estar aquí… ¡pero si estás muerto!»',
      copies: 1,
      image: `${base}/horror/no-puedes-estar-aqui.webp`,
      text: 'Según las Víctimas muertas: 0, caes Dormida; 1-3, +1 Sed de Sangre; 4 o más, +2 Sed de Sangre. Después: el más cercano ▶ mover ▶ atacar.',
      effects: [custom('df-dead-count'), ka('nearest', 1, 1)],
    },
    {
      id: 'coge-tu-crucifijo',
      name: 'Coge tu crucifijo',
      copies: 1,
      image: `${base}/horror/coge-tu-crucifijo.webp`,
      text: 'Si tienes un Crucifijo puedes descartarlo para ignorar el resto de esta carta. Si no: el más cercano ▶ mover ▶ atacar, y otra vez el más cercano ▶ mover ▶ atacar.',
      effects: [custom('df-crucifix-gate'), ka('nearest', 1, 1), ka('nearest', 1, 1)],
    },
    {
      id: 'omg-dedos',
      name: '«OMG… ¡Se está cortando sus propios dedos!»',
      copies: 1,
      image: `${base}/horror/omg-dedos.webp`,
      text: 'El más cercano ▶ mover ▶ mover. El Dr. Fright recibe 1 de daño, a menos que solo le quede una ficha de Vida Final. Si recibe daño: +3 Terror y tú y todas las Víctimas de su espacio entráis en pánico.',
      effects: [ka('nearest', 2, 0), custom('df-omg')],
    },
    {
      id: 'mejor-cerrar-la-puerta',
      name: 'Mejor cerrar la puerta',
      copies: 1,
      image: `${base}/horror/mejor-cerrar-la-puerta.webp`,
      text: 'La Chica Final ▶ mover. Después: el más cercano ▶ atacar. Durante la siguiente fase de Acción no puedes moverte dentro de ninguna Casa ocupada por una Víctima.',
      effects: [ka('finalGirl', 1, 0), ka('nearest', 0, 1), custom('df-lock-houses')],
    },
    {
      id: 'no-sabias-muertos',
      name: '«¿No sabías que ya estaban muertos?»',
      copies: 1,
      image: `${base}/horror/no-sabias-muertos.webp`,
      text: 'Si no has salvado a ninguna Víctima o has girado tu carta de Chica Final, descarta esta carta y resuelve la siguiente. Si no: quita 1 Víctima de tu espacio de Víctimas Salvadas. La Víctima más cercana ▶ mover ▶ atacar.',
      effects: [custom('df-undead'), ka('victim', 1, 1)],
    },
    {
      id: 'mejor-estar-despierta',
      name: 'Mejor estar despierta',
      copies: 1,
      image: `${base}/horror/mejor-estar-despierta.webp`,
      text: 'Si estás Despierta, tira 1 dado menos en las Tiradas de Horror de la siguiente fase de Acción. Si estás Dormida, resuelve inmediatamente todas las cartas restantes de la Sala de Calderas. Después: el más cercano ▶ mover ▶ atacar.',
      effects: [custom('df-better-awake'), ka('nearest', 1, 1)],
    },
    {
      id: 'tengo-tanto-sueno',
      name: '«¡Tengo tanto sueño…!»',
      copies: 1,
      image: `${base}/horror/tengo-tanto-sueno.webp`,
      text: 'Si estás Despierta tira un dado: si es menor que el nivel de Horror, caes Dormida. Si estás Dormida, resuelve una carta de la Sala de Calderas y, si recibes daño, +1 Terror. Después: la Víctima más cercana ▶ mover.',
      effects: [custom('df-sleepy'), ka('victim', 1, 0)],
    },
    {
      id: 'realidad-borrosa',
      name: 'Realidad borrosa',
      copies: 1,
      image: `${base}/horror/realidad-borrosa.webp`,
      text: 'Hasta la próxima fase de Terror, el Dr. Fright y tú podéis haceros daño aunque estés Despierta. El más cercano ▶ mover ▶ atacar.',
      effects: [custom('df-blurred'), ka('nearest', 1, 1)],
    },
    {
      id: 'ewwww',
      name: '«¡Ewwww! ¡Es desagradable!»',
      copies: 1,
      image: `${base}/horror/ewwww.webp`,
      text: '+2 Terror.',
      effects: [terror(2)],
    },
    {
      id: 'marcado-para-la-muerte',
      name: 'Marcado para la muerte',
      copies: 1,
      image: `${base}/horror/marcado-para-la-muerte.webp`,
      text: 'Hasta la siguiente fase de Terror, todas las Víctimas de tu espacio entran en pánico. La Chica Final ▶ mover. Después: el más cercano ▶ atacar. Si el Dr. Fright no te ataca y estás Despierta, caes inmediatamente Dormida.',
      effects: [custom('df-marked'), ka('finalGirl', 1, 0), custom('df-attack-mark'), ka('nearest', 0, 1), custom('df-marked-after')],
    },
    {
      id: 'si-esto-es-un-sueno',
      name: '«Si esto es un sueño, entonces puedo…»',
      copies: 1,
      image: `${base}/horror/si-esto-es-un-sueno.webp`,
      text: 'Si estás Despierta, descarta esta carta y resuelve la siguiente. Si no, puedes aumentar la Sed de Sangre en 1 para elegir: coger el Objeto superior de cualquier mazo, moverte a cualquier espacio o ganar 4 de Tiempo.',
      effects: [custom('df-dream')],
    },
    {
      id: 'frankie-viene',
      name: 'Frankie viene a por ti',
      copies: 1,
      image: `${base}/horror/frankie-viene.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Terror. Si no: la Víctima más cercana ▶ mover. Si el Dr. Fright está con al menos 1 Víctima: +2 Terror; si no, +1 Terror.',
      requiresVictims: true,
      effects: [ka('victim', 1, 0), custom('df-frankie')],
    },
    {
      id: 'jamas-volver-a-dormir',
      name: 'Jamás volver a dormir',
      copies: 1,
      image: `${base}/horror/jamas-volver-a-dormir.webp`,
      text: '+1 Terror. Caes Dormida. Si ya estabas Dormida puedes reiniciar el mazo de la Sala de Calderas; si no quieres, resuelve una carta adicional de la Sala de Calderas al final de la fase del Asesino.',
      effects: [terror(1), custom('df-never-sleep')],
    },
    {
      id: 'sueno-interminable',
      name: 'Sueño interminable',
      copies: 1,
      image: `${base}/horror/sueno-interminable.webp`,
      text: 'Poder Oscuro Menor (1 Vida). Caes Dormida. Mientras esta carta esté en juego debes estar Dormida; reinicia la Sala de Calderas nada más salir.',
      effects: [custom('df-sleep')],
      minorDarkPower: { health: 1, custom: 'mdp-ml-endless' },
    },
    {
      id: 'busqueda-infernal',
      name: 'Búsqueda infernal',
      copies: 1,
      image: `${base}/horror/busqueda-infernal.webp`,
      text: 'Poder Oscuro Menor (2 Vidas). Mientras estás Dormida, debes resolver una carta adicional de la Sala de Calderas al final de la fase del Asesino si es posible.',
      effects: [],
      minorDarkPower: { health: 2, custom: 'mdp-ml-search' },
    },
  ],
  specialRules:
    'Despierta / Dormida: Despierta, el Dr. Fright no puede atacarte ni tú a él. Dormida (en la Sala de Calderas) pueden atacarse y las Víctimas no te siguen ni se pueden salvar. Al final de cada fase del Asesino, estando Dormida, resuelves una carta de la Sala de Calderas; si el Dr. Fright aparece en la zona revelada, te ataca. Las revelas deslizando el mazo arriba, abajo, izquierda o derecha.',
};
