import type { Effect, Killer, KillerAction } from '../../types';

const base = 'assets/killers/geppetto';
const ka = (
  target: KillerAction['target'],
  moves: number,
  attacks: number,
  opts: { actor?: KillerAction['actor']; per?: Effect[]; attackFirst?: boolean } = {},
): Effect => ({
  kind: 'killerAction',
  action: {
    target,
    moves,
    attacks,
    ...(opts.actor ? { actor: opts.actor } : {}),
    ...(opts.per ? { perVictimKilled: opts.per } : {}),
    ...(opts.attackFirst ? { attackFirst: true } : {}),
  },
});
const custom = (id: string): Effect => ({ kind: 'custom', id });
const terror = (amount: number): Effect => ({ kind: 'terror', amount });
const row = (attack: number, move: number, effects: Effect[] = [], revealDarkPower = false) => ({
  attack,
  move,
  effects,
  ...(revealDarkPower ? { revealDarkPower } : {}),
});
const event: Effect = { kind: 'drawEvent' };

export const GEPPETTO: Killer = {
  id: 'geppetto',
  name: 'Geppetto',
  film: 'carnival',
  icon: 'tophat',
  board: `${base}/board.webp`,
  cover: `${base}/cover.webp`,
  token: `${base}/token.webp`,
  select: `${base}/select.webp`,
  startTerror: 4,
  health: 8,
  // Medidor de Sed de Sangre, de abajo a arriba (leído del tablero). Dos filas roban un Evento.
  bloodlust: [
    row(1, 1),
    row(1, 1),
    row(1, 1),
    row(1, 2, [], true),
    row(1, 2),
    row(2, 2),
    row(2, 3, [event]),
    row(2, 3),
    row(2, 3, [event]),
  ],
  // "Descarta 1 carta de Terror"
  bloodlustMaxEffect: [custom('discard-next-horror')],
  bloodlustMaxText: 'se descarta la siguiente carta de Horror',
  minion: {
    name: 'Marioneta',
    plural: 'Marionetas',
    count: 3,
    health: 1,
    attack: 1,
    tokens: [`${base}/minions/marioneta-1.webp`, `${base}/minions/marioneta-2.webp`, `${base}/minions/marioneta-3.webp`],
    reference: `${base}/special/marionetas.webp`,
    text:
      'Esbirros (3 en total). Tienen 1 Vida, Ataque 1 y el Movimiento de Geppetto. Deben terminar su movimiento a menos de 2 espacios de Geppetto. ' +
      'Hasta el Gran Final, cada fase del Asesino aparece una Marioneta de la casilla Listo; las destruidas vuelven a Listo en la siguiente.',
  },
  // Reverso del Gran Final. Línea M: aparece 1 Marioneta ▶ Víctima más cercana ▶ mover. Línea K: lo más cercano ▶ atacar.
  initialMinionAction: [custom('minion-spawn'), ka('victim', 1, 0, { actor: 'minions' })],
  initialAction: [ka('nearest', 0, 1, { actor: 'killer' })],
  finaleBack: `${base}/finale/back.webp`,
  darkPowerBack: `${base}/dark-power/back.webp`,
  finales: [
    {
      id: 'hice-a-tus-amigos',
      name: 'Hice a tus amigos',
      image: `${base}/finale/hice-a-tus-amigos.webp`,
      minionAction: [ka('finalGirl', 1, 1, { actor: 'minions' })],
      finalAction: [ka('finalGirl', 1, 1, { actor: 'killer' })],
      text: 'Durante la fase del Asesino, las Víctimas actúan como Marionetas (resuelven la acción de Esbirro); el resto del tiempo son Víctimas normales. Puedes atacar y matar Víctimas si quieres (sube la Sed de Sangre).',
      custom: 'finale-friends',
    },
    {
      id: 'sin-ataduras',
      name: 'Sin ataduras',
      image: `${base}/finale/sin-ataduras.webp`,
      minionAction: [ka('nearest', 1, 1, { actor: 'minions' })],
      finalAction: [ka('nearest', 2, 1, { actor: 'killer' })],
      text: 'Los movimientos de las Marionetas ya no están atados a Geppetto: pueden moverse por todas partes. Cuando se muevan, pueden moverse 1 espacio adicional.',
      custom: 'finale-unbound',
    },
    {
      id: 'les-recuerdas',
      name: '¿Les recuerdas?',
      image: `${base}/finale/les-recuerdas.webp`,
      minionAction: [ka('nearest', 1, 1, { actor: 'minions' })],
      finalAction: [ka('finalGirl', 1, 2, { actor: 'killer' })],
      text: 'Cuando se revele, coloca todas las Marionetas restantes en el tablero. Cuando se muevan las Marionetas, se mueven 1 espacio menos de lo normal.',
      custom: 'finale-remember',
    },
  ],
  darkPowers: [
    {
      id: 'abominacion-masiva',
      name: 'Abominación masiva',
      image: `${base}/dark-power/abominacion-masiva.webp`,
      text: 'Cada Marioneta ignora el primer daño que recibe cada turno.',
      custom: 'dp-massive-abomination',
    },
    {
      id: 'injerto-de-armas',
      name: 'Injerto de armas',
      image: `${base}/dark-power/injerto-de-armas.webp`,
      text: 'Las Marionetas ahora hacen 2 de daño al atacar.',
      custom: 'dp-weapon-graft',
    },
    {
      id: 'maestro-inmortal',
      name: 'Maestro inmortal',
      image: `${base}/dark-power/maestro-inmortal.webp`,
      text: 'Si todas las Marionetas están en el tablero, Geppetto no puede morir. Cualquier daño que pudiera retirar su ficha de Vida Final se ignora.',
      custom: 'dp-immortal-master',
    },
    {
      id: 'unete-a-la-familia',
      name: 'Únete a la familia',
      image: `${base}/dark-power/unete-a-la-familia.webp`,
      text: 'Poder Oscuro Épico. Durante la fase del Asesino, si las 3 Marionetas están en tu espacio, pierdes toda la Vida restante. Todavía resuelves tu ficha de Vida Final de forma normal.',
      epic: true,
      custom: 'dp-join-family',
    },
  ],
  horror: [
    {
      id: 'loca-risa-interminable',
      name: 'Loca risa interminable',
      copies: 1,
      image: `${base}/horror/loca-risa-interminable.webp`,
      text: 'Todas las Víctimas de tu espacio y de los adyacentes entran en pánico. Las Víctimas en un espacio con un Enemigo son asesinadas. Si estás con o adyacente a Geppetto, pierdes Vida igual a su Valor de Ataque. Si ninguna Víctima fue asesinada y no sufriste daño, resuelve la siguiente carta de Terror.',
      effects: [custom('cn-loca-risa')],
    },
    {
      id: 'piezas-de-repuesto',
      name: 'Piezas de repuesto',
      copies: 1,
      image: `${base}/horror/piezas-de-repuesto.webp`,
      text: 'Coloca 2 nuevas Víctimas en el punto de partida de Geppetto. Luego coloca a Geppetto en el espacio de la Víctima más cercana. Objetivo el más cercano ▶ atacar. Por cada Víctima que muera: +1 Sed de Sangre y Geppetto recupera 1 Vida.',
      effects: [
        { kind: 'placeVictims', count: 2, where: { at: 'killerStart' } },
        custom('cn-spare-parts'),
        ka('nearest', 0, 1, { per: [{ kind: 'bloodlust', amount: 1 }, { kind: 'killerHeal', amount: 1 }] }),
      ],
    },
    {
      id: 'seras-un-divertido-nuevo-juguete',
      name: '«Serás un divertido nuevo juguete…»',
      copies: 1,
      image: `${base}/horror/seras-un-divertido-nuevo-juguete.webp`,
      text: '+2 Terror. Objetivo el más cercano ▶ mover ▶ atacar.',
      effects: [terror(2), ka('nearest', 1, 1)],
    },
    {
      id: 'encerrado-y-sin-lugar-donde-ir',
      name: 'Encerrado y sin lugar donde ir',
      copies: 1,
      image: `${base}/horror/encerrado-y-sin-lugar-donde-ir.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Terror. Si no: +2 Terror. Cada Víctima que está con o adyacente al espacio de una Marioneta entra en pánico. Si una Víctima entra en pánico a un espacio con una Marioneta, muere inmediatamente.',
      requiresVictims: true,
      effects: [terror(2), custom('cn-trapped')],
    },
    {
      id: 'hacer-o-romper',
      name: 'Hacer o romper',
      copies: 1,
      image: `${base}/horror/hacer-o-romper.webp`,
      text: 'Tira un dado. Debes perder Vida igual a la mitad del resultado (redondeando hacia arriba) o, en su lugar, mueren ese mismo número de Víctimas.',
      effects: [custom('cn-do-or-die')],
    },
    {
      id: 'no-hay-salida',
      name: 'No hay salida',
      copies: 1,
      image: `${base}/horror/no-hay-salida.webp`,
      text: '+1 Terror. Coloca a Geppetto y a cada Marioneta en un espacio de Salida (distribuye con igualdad). Objetivo el más cercano ▶ mover ▶ atacar.',
      effects: [terror(1), custom('cn-no-exit'), ka('nearest', 1, 1)],
    },
    {
      id: 'traedmela',
      name: '«¡Traédmela!»',
      copies: 1,
      image: `${base}/horror/traedmela.webp`,
      text: 'La Marioneta más cercana a ti: objetivo la Chica Final ▶ mover ▶ atacar. Si has recibido daño de la Marioneta, te mueven 1 espacio más hacia Geppetto. Si estás en el espacio de Geppetto o no hay Marionetas en tu espacio, descarta esta carta. Si no, resuélvela de nuevo desde el inicio.',
      effects: [custom('cn-bring-her')],
    },
    {
      id: 'showman-maestro',
      name: 'Showman maestro',
      copies: 1,
      image: `${base}/horror/showman-maestro.webp`,
      text: 'Coloca a Geppetto en tu espacio. Pon una Marioneta en cada espacio adyacente si es posible. Objetivo el más cercano ▶ atacar.',
      effects: [custom('cn-showman'), ka('nearest', 0, 1)],
    },
    {
      id: 'nos-tienen-completamente-rodeados',
      name: '«¡Nos tienen completamente rodeados!»',
      copies: 1,
      image: `${base}/horror/nos-tienen-completamente-rodeados.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Terror. Si no: +1 Terror. Objetivo la Víctima más cercana ▶ mover ▶ atacar.',
      requiresVictims: true,
      effects: [terror(1), ka('victim', 1, 1)],
    },
    {
      id: 'baila-muneco',
      name: '«¡Baila muñeco!»',
      copies: 1,
      image: `${base}/horror/baila-muneco.webp`,
      text: 'Haz una Tirada de Terror. Con éxito: mueve todas las Marionetas 1 espacio hacia ti o hacia la Víctima más cercana (eliges). Sin éxito: mata a una Víctima en tu espacio; si no hay, +2 Terror.',
      effects: [custom('cn-dance')],
    },
    {
      id: 'vienen-por-todas-partes',
      name: '«¡Vienen por todas partes!»',
      copies: 1,
      image: `${base}/horror/vienen-por-todas-partes.webp`,
      text: 'Tira un dado. Si el resultado es menor que el nivel de Horror, las Marionetas que quedan (da igual su estado) aparecen en el espacio de Geppetto. Las Marionetas sólo: objetivo la Chica Final ▶ mover ▶ mover ▶ atacar.',
      effects: [custom('cn-everywhere'), ka('finalGirl', 2, 1, { actor: 'minions' })],
    },
    {
      id: 'cielo-santo-esos-son-nuestros-amigos',
      name: '«¡Cielo santo! ¿Esos son nuestros amigos?»',
      copies: 1,
      image: `${base}/horror/cielo-santo-esos-son-nuestros-amigos.webp`,
      text: 'Objetivo el más cercano ▶ mover ▶ atacar. Tira un dado por cada Víctima con o adyacente a una Marioneta: 1-5 mueve la Víctima hacia la Marioneta; 6 mueve la Víctima 1 espacio en cualquier dirección. Después: objetivo el más cercano ▶ atacar.',
      effects: [ka('nearest', 1, 1), custom('cn-friends'), ka('nearest', 0, 1)],
    },
    {
      id: 'cuerdas-cuchilla-de-marioneta',
      name: 'Cuerdas cuchilla de Marioneta',
      copies: 1,
      image: `${base}/horror/cuerdas-cuchilla-de-marioneta.webp`,
      text: 'Las Víctimas con o adyacentes a Geppetto son asesinadas. Pierdes 2 Vida si estás con o adyacente a Geppetto (puedes reducir el daño en 1 por cada carta de Caminar o Correr que descartes). Si ninguna Víctima murió y no recibiste daño, resuelve la siguiente carta de Terror.',
      effects: [custom('cn-blades')],
    },
    {
      id: 'me-estan-ganando',
      name: '«¡Me están ganando!»',
      copies: 1,
      image: `${base}/horror/me-estan-ganando.webp`,
      text: 'Tira un dado. Si el resultado es menor que el nivel de Horror, pierdes Tiempo igual al nivel de Horror. Las Marionetas sólo: objetivo la Chica Final ▶ mover.',
      effects: [custom('cn-winning'), ka('finalGirl', 1, 0, { actor: 'minions' })],
    },
    {
      id: 'soy-una-marioneta',
      name: '«¿Soy una marioneta?»',
      copies: 1,
      image: `${base}/horror/soy-una-marioneta.webp`,
      text: 'Poder Oscuro Menor (2 Vidas). Si comienzas tu turno a más de 2 espacios de Geppetto, pierdes Vida igual a su Valor de Ataque actual.',
      effects: [],
      minorDarkPower: { health: 2, custom: 'mdp-am-i-puppet' },
    },
    {
      id: 'marionetas-por-doquier',
      name: 'Marionetas por doquier',
      copies: 1,
      image: `${base}/horror/marionetas-por-doquier.webp`,
      text: 'Poder Oscuro Menor (2 Vidas). Cada vez que una Víctima es asesinada en tu espacio o en uno adyacente, +1 Terror.',
      effects: [],
      minorDarkPower: { health: 2, custom: 'mdp-puppets-everywhere' },
    },
  ],
  specialRules:
    'Marionetas (Esbirros): 3 fichas con 1 Vida y Ataque 1; su Movimiento es el de Geppetto. Los Esbirros siempre actúan antes que el Asesino. Deben terminar su movimiento a menos de 2 espacios de Geppetto.',
};
