import type { Effect, Killer, KillerAction } from '../../types';

const base = 'assets/killers/hans';
const ka = (target: KillerAction['target'], moves: number, attacks: number, perVictimKilled?: Effect[]): Effect => ({
  kind: 'killerAction',
  action: { target, moves, attacks, ...(perVictimKilled ? { perVictimKilled } : {}) },
});
const row = (attack: number, move: number, effects: Effect[] = [], revealDarkPower = false) => ({
  attack,
  move,
  effects,
  ...(revealDarkPower ? { revealDarkPower } : {}),
});
const terrorUp: Effect = { kind: 'terror', amount: 1 };

export const HANS: Killer = {
  id: 'hans',
  name: 'Hans the Butcher',
  film: 'happy-trails',
  icon: 'pig',
  board: `${base}/board.webp`,
  cover: `${base}/cover.webp`,
  token: `${base}/token.webp`,
  select: `${base}/select.webp`,
  startTerror: 4,
  health: 12,
  // Medidor de Sed de Sangre, de abajo a arriba (leído del tablero).
  bloodlust: [
    row(2, 1),
    row(2, 1),
    row(2, 1, [terrorUp]),
    row(2, 1),
    row(3, 1, [terrorUp]),
    row(3, 2, [], true),
    row(3, 2),
    row(3, 2, [terrorUp]),
    row(4, 2),
    row(4, 2, [terrorUp]),
    row(5, 3),
  ],
  // "Hans se recupera ♥ ▶ Descarta la siguiente carta de Horror"
  bloodlustMaxEffect: [{ kind: 'killerHeal', amount: 1 }, { kind: 'custom', id: 'discard-next-horror' }],
  // Reverso del Gran Final: objetivo el más cercano ▶ ataque.
  initialAction: [ka('nearest', 0, 1)],
  finaleBack: `${base}/finale/back.webp`,
  darkPowerBack: `${base}/dark-power/back.webp`,
  finales: [
    {
      id: 'oscuro-lugubre-tenebroso',
      name: 'Oscuro. Lúgubre. Tenebroso.',
      image: `${base}/finale/oscuro-lugubre-tenebroso.webp`,
      finalAction: [ka('nearest', 2, 1)],
      text: 'Roba una segunda carta de Poder Oscuro cuando esta sea revelada.',
      custom: 'finale-second-dark-power',
    },
    {
      id: 'sed-de-sangre',
      name: 'Sed de sangre',
      image: `${base}/finale/sed-de-sangre.webp`,
      finalAction: [{ kind: 'bloodlust', amount: 1 }, ka('nearest', 2, 1)],
    },
    {
      id: 'bano-de-sangre',
      name: 'Baño de sangre',
      image: `${base}/finale/bano-de-sangre.webp`,
      finalAction: [ka('nearest', 2, 2)],
    },
  ],
  darkPowers: [
    {
      id: 'la-masacre-del-martillo',
      name: 'La masacre del martillo',
      image: `${base}/dark-power/la-masacre-del-martillo.webp`,
      text: 'Por cada ataque, Hans te ataca a ti y a cada Víctima de su zona una vez.',
      custom: 'dp-hammer-massacre',
    },
    {
      id: 'oscura-obsesion',
      name: 'Oscura obsesión',
      image: `${base}/dark-power/oscura-obsesion.webp`,
      text: 'Cada vez que Hans te ataca al menos una vez, ataca una vez más.',
      custom: 'dp-dark-obsession',
    },
    {
      id: 'alimentar',
      name: 'Alimentar',
      image: `${base}/dark-power/alimentar.webp`,
      text: 'Por cada Víctima que Hans mata, recupera 1 Vida.',
      custom: 'dp-feed',
    },
    {
      id: 'frenesi-de-sangre',
      name: 'Frenesí de sangre',
      image: `${base}/dark-power/frenesi-de-sangre.webp`,
      text: 'Poder Oscuro Épico. Por cada Víctima que Hans mata, +1 Sed de Sangre adicional.',
      epic: true,
      custom: 'dp-blood-frenzy',
    },
  ],
  horror: [
    {
      id: 'balanceando-su-martillo',
      name: '«Él seguía balanceando su martillo y matando y matando»',
      copies: 1,
      image: `${base}/horror/balanceando-su-martillo.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Horror. En caso contrario: objetivo la Víctima más cercana ▶ mover ▶ atacar, dos veces.',
      requiresVictims: true,
      effects: [ka('victim', 1, 1), ka('victim', 1, 1)],
    },
    {
      id: 'el-ya-esta-ahi',
      name: '«¡Él ya… está ahí!»',
      copies: 2,
      image: `${base}/horror/el-ya-esta-ahi.webp`,
      text: '+2 Terror. Objetivo el más cercano ▶ mover ▶ mover.',
      effects: [{ kind: 'terror', amount: 2 }, ka('nearest', 2, 0)],
    },
    {
      id: 'sigue-viniendo',
      name: '«¡Sigue viniendo!»',
      copies: 3,
      image: `${base}/horror/sigue-viniendo.webp`,
      text: '+1 Terror. Objetivo el más cercano ▶ mover ▶ atacar.',
      effects: [terrorUp, ka('nearest', 1, 1)],
    },
    {
      id: 'ha-salido-de-ninguna-parte',
      name: '«¡Ha salido de ninguna parte!»',
      copies: 1,
      image: `${base}/horror/ha-salido-de-ninguna-parte.webp`,
      // FAQ: el objetivo más lejano es la Víctima más lejana de Hans, no la Chica Final.
      text: 'Coloca a Hans con el Objetivo más lejano posible (la Víctima más lejana). +1 Terror. Roba la siguiente carta de Horror.',
      effects: [{ kind: 'custom', id: 'hans-teleport-farthest-victim' }, terrorUp, { kind: 'drawHorror' }],
    },
    {
      id: 'quiere-sangre-fresca',
      name: '«¡Quiere sangre fresca!»',
      copies: 2,
      image: `${base}/horror/quiere-sangre-fresca.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Horror. Objetivo la Víctima más cercana ▶ mover ▶ mover ▶ atacar.',
      requiresVictims: true,
      effects: [ka('victim', 2, 1)],
    },
    {
      id: 'terrorifica-fiebre-del-martillo',
      name: '«Terrorífica fiebre del martillo»',
      copies: 1,
      image: `${base}/horror/terrorifica-fiebre-del-martillo.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Horror. En caso contrario: objetivo la Víctima más cercana ▶ mover ▶ mover ▶ atacar ▶ atacar. Por cada Víctima muerta durante este ataque: +1 Terror.',
      requiresVictims: true,
      effects: [ka('victim', 2, 2, [terrorUp])],
    },
    {
      id: 'hans-me-quiere-a-mi',
      name: '«Hans me quiere a mí. Siempre me quiso a mí.»',
      copies: 2,
      image: `${base}/horror/hans-me-quiere-a-mi.webp`,
      text: 'Objetivo la Chica Final ▶ mover ▶ mover ▶ atacar.',
      effects: [ka('finalGirl', 2, 1)],
    },
    {
      id: 'rabia-malvada',
      name: 'Rabia malvada',
      copies: 1,
      image: `${base}/horror/rabia-malvada.webp`,
      text: 'Poder Oscuro Menor (2 Vidas). Hans hace 1 de daño adicional por cada ataque.',
      effects: [],
      minorDarkPower: { health: 2, custom: 'mdp-wicked-rage' },
    },
    {
      id: 'tomando-recuerdos',
      name: 'Tomando recuerdos',
      copies: 1,
      image: `${base}/horror/tomando-recuerdos.webp`,
      text: 'Si no hay Víctimas en el tablero, descarta y roba la siguiente carta de Horror. En caso contrario: objetivo la Víctima más cercana ▶ mover ▶ atacar ▶ atacar. Por cada Víctima asesinada durante la fase del Asesino: +1 Sed de Sangre.',
      requiresVictims: true,
      effects: [ka('victim', 1, 2), { kind: 'custom', id: 'bloodlust-per-victim-killed-this-killer-phase' }],
    },
    {
      id: 'banquete-oscuro',
      name: 'Banquete oscuro',
      copies: 1,
      image: `${base}/horror/banquete-oscuro.webp`,
      // Decisión del usuario: cuenta todas las Víctimas del espacio de Muertas.
      text: '+1 Terror. Por cada Víctima muerta (en el espacio de Muertas), Hans recupera 1 Vida.',
      effects: [terrorUp, { kind: 'custom', id: 'killer-heal-per-dead-victim' }],
    },
    {
      id: 'velocidad-endemoniada',
      name: 'Velocidad endemoniada',
      copies: 1,
      image: `${base}/horror/velocidad-endemoniada.webp`,
      text: 'Poder Oscuro Menor (2 Vidas). Hans se mueve 1 zona adicional por cada icono de movimiento.',
      effects: [],
      minorDarkPower: { health: 2, custom: 'mdp-demonic-speed' },
    },
  ],
  specialRules: 'No hay reglas especiales para Hans.',
};
